apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.identity/client-id: fe075af4-7a7b-4687-946f-f5e24e74cc8e
  labels:
    azure.workload.identity/use: "true"